// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CopaPrimavera.API.Migrations
{
    [DbContext(typeof(DbbContext))]
    partial class DbbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CopaPrimavera.Modelos.EncuentroLlave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("EncuentrosLlaves");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.EstadisticaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Derrotas")
                        .HasColumnType("integer");

                    b.Property<int>("Empates")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("integer");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("integer");

                    b.Property<int>("Juegos")
                        .HasColumnType("integer");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("integer");

                    b.Property<int>("Victorias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("EstadisticasEquipos");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.EstadisticaJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Goles")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("EstadisticasJugadores");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Gol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Autogol")
                        .HasColumnType("boolean");

                    b.Property<int?>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Goles");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("Goles")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("Fase")
                        .HasColumnType("integer");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsJugado")
                        .HasColumnType("boolean");

                    b.Property<int?>("PenalesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("PenalesVisitante")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Programado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Suspension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UntilPartidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("Suspensiones");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxEquipos")
                        .HasColumnType("integer");

                    b.Property<int>("MinEquipos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.EncuentroLlave", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Torneo", "Torneo")
                        .WithMany("EncuentrosLlave")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Equipo", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Torneo", "Torneo")
                        .WithMany("Equipos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.EstadisticaEquipo", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Equipo", "Equipo")
                        .WithOne("Estadistica")
                        .HasForeignKey("CopaPrimavera.Modelos.EstadisticaEquipo", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.EstadisticaJugador", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Gol", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId");

                    b.HasOne("CopaPrimavera.Modelos.Partido", "Partido")
                        .WithMany("Goles")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Grupo", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Torneo", null)
                        .WithMany("Grupos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Jugador", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Partido", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaPrimavera.Modelos.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaPrimavera.Modelos.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Suspension", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Tarjeta", b =>
                {
                    b.HasOne("CopaPrimavera.Modelos.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaPrimavera.Modelos.Partido", "Partido")
                        .WithMany("Tarjetas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Equipo", b =>
                {
                    b.Navigation("Estadistica");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Partido", b =>
                {
                    b.Navigation("Goles");

                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("CopaPrimavera.Modelos.Torneo", b =>
                {
                    b.Navigation("EncuentrosLlave");

                    b.Navigation("Equipos");

                    b.Navigation("Grupos");

                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
